# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool
#组件参数配置
inputs:
  name: ${name}_scf
  namespace: default
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-shanghai # 函数所在区域，默认广州
  description: 哔哩哔哩每日任务
  memorySize: 128
  initTimeout: 30
  timeout: 60
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    timer: # 每日任务触发器
      parameters:
        name: DailyTask
        cronExpression: "0 30 12 * * * *"
        enable: true
        argument: Daily
    timer: # 天选抽奖触发器
      parameters:
        name: LiveLotteryTask
        cronExpression: "0 0 */4 * * * *"
        enable: true
        argument: LiveLottery
    timer: # 自动取关
      parameters:
        name: UnfollowBatchedTask
        cronExpression: "0 0 0 * * MON *"
        enable: true
        argument: UnfollowBatched
    # timer: # 大会员积分
    #   parameters:
    #     name: VipBigPointTask
    #     cronExpression: "0 07 01 * * * *"
    #     enable: true
    #     argument: VipBigPoint
  environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: SESSDATA=82217463%2C1758103913%2C98071%2A31CjB66j9OC1sxUvyeTYeC540SAMnagQK1FCQXwzwmdQbz2OA8timAhHevgGRtF1_KybESVkhfMUQ2RUR3dFpJYmpNWjY5NmVXM2stbFNYMnBnZTB2U1BkMTN5SGNqSmN3Yk5kSl82ZzA2R0JKZW1lU3luUlZjWVhKUndRWWVjZ18wWl9EanpuZDNnIIEC; bili_jct=778f2c8f77f9af2095f09d056ef3071e; # cookie，必填
